server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://localhost:8081
          predicates:
            - Path=/books/**
          filters:
            - TokenRelay # Token relay filter appends the oauth (or jwt) token to request header before forwarding requests
